services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-multistage-app
    ports:
      - "8080:8080"
    environment:
      APP_NAME: "My DevOps Lab"
      APP_PORT: 8080
    restart: unless-stopped
